version: '3.0'
services:
  react:
    image: react-app:latest 
    container_name: react-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 7003:80
    networks:
      - reactnet 

networks: 
  reactnet: